добавил логи плюс исправил feign
sergey-oreshkin/megamarket-bot pull request #21
Opened 2023-05-03 12:11 UTC by iDmitrySoldatov

2023-05-03 13:52 UTC, sergey-oreshkin requested changes

2023-05-03 13:52 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/handler/impl/AllHandler.java
>              log.error("Error work /all request");
надо логировать саму ошибку или хотябы статус код. можно получить e.status()
и так везде. логировать что просто произошла какая то ошибка - малоинформативно.

2023-05-03 13:52 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/feign/MarketServiceClient.java
> +    @GetMapping("/carts/users")
по моему если ты передаешь PathVariable то это тоже надо прописывать в урле - /carts/users/{userId}

2023-05-03 13:52 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/handler/impl/ListHandler.java
>              log.error("Soap server error /list method");
тоже логируй саму ошибку или хотябы пиши e.printStackTrace(), чтоб в логах было видно что не так..

2023-05-03 13:52 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/handler/impl/InventoryHandler.java
> -                    + storageService.getAllByUserId(sellerId);
где то есть -  log.info("Send currency /cart response"); где то нет. если уж начал пиши везде, кто будет логи смотреть, будет ожидать именно этого.

2023-05-03 13:52 UTC, sergey-oreshkin commented on gateway/src/main/resources/application.properties
> +market-service.url=${MARKET_SERVICE_URL:http://localhost:8081/}
адрес соап сервера тоже надо брать из пропертей и переменных окружения, чтоб не лазить не менять это по коду

2023-05-03 16:39 UTC, iDmitrySoldatov commented on gateway/src/main/java/group/megamarket/gateway/feign/MarketServiceClient.java
> +    @GetMapping("/carts/users")
без этого должно работать

2023-05-04 03:16 UTC, sergey-oreshkin approved these changes

2023-05-04 09:18 UTC, oks29b approved these changes

2023-05-04 09:18 UTC, merged