создание юзер сервиса
sergey-oreshkin/megamarket-bot pull request #4
Opened 2023-04-20 19:48 UTC by oks29b

2023-04-27 05:04 UTC, iDmitrySoldatov reviewed
javadoc комментарии по файлу rules
думаю в контроллерах надо интеграционный тест делать, а остальные просто юнит
маппинг наверное лучше делать в контроллере.

2023-04-27 05:30 UTC, sergey-oreshkin requested changes

2023-04-27 05:30 UTC, sergey-oreshkin commented on userservice/src/main/java/group/megamarket/userservice/service/impl/RequestServiceImpl.java
> +        if (user.getRoles().contains(role)) {
это можно объеденить if(user.getRole()!=null && user.getRoles().contains(role))

2023-04-27 05:30 UTC, sergey-oreshkin commented on userservice/src/main/java/group/megamarket/userservice/service/impl/RequestServiceImpl.java
> +        //it's right?
вопросы в английском начинаются с глагола. is it right?

2023-04-27 05:30 UTC, sergey-oreshkin commented on userservice/src/main/java/group/megamarket/userservice/service/impl/RequestServiceImpl.java
> +        return repository.findAll();
давай будем отдавать отсортированными по времени, чтоб новые были с начала, и например, только за последние 3 дня. а то мы их не отмечаем что они удовлетворены и в реальном приложении через какое то время тут начнет возвращатся простыня из тысяч запросов..
для этого конечно придется добавить в таблицу поле со временем создания

2023-04-28 13:31 UTC, oks29b commented on userservice/src/main/java/group/megamarket/userservice/service/impl/RequestServiceImpl.java
> +        if (user.getRoles().contains(role)) {
Не, нельзя, ты же посмотри что я делаю)

2023-04-28 16:47 UTC, oks29b commented on userservice/src/main/java/group/megamarket/userservice/service/impl/RequestServiceImpl.java
> +        return repository.findAll();
давай будем делать в будущем)

2023-04-28 16:47 UTC, oks29b commented on userservice/src/main/java/group/megamarket/userservice/service/impl/RequestServiceImpl.java
> +        //it's right?
Ок

2023-04-28 16:49 UTC, sergey-oreshkin approved these changes

2023-04-28 18:09 UTC, iDmitrySoldatov approved these changes

2023-04-28 18:10 UTC, merged