Gateway
sergey-oreshkin/megamarket-bot pull request #7
Opened 2023-04-27 10:08 UTC by iDmitrySoldatov

2023-04-28 14:39 UTC, sergey-oreshkin requested changes
то что в хэндлере одном написал про валидацию и try касается всех хэндлеров

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/pom.xml
> +<!--                                       </wsdlFiles>&ndash;&gt;-->
не нужно оставлять закомментированый мусор

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/controller/Bot.java
> +            sendResponse(chatId, handler.handle(update));
getBean надо в try завернуть, а то это опасная операция

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/dto/market/OrderRequest.java
> +public class OrderRequest {
у дто в названии должно быть dto

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/dto/market/OrderResponse.java
> +public class OrderResponse {
тоже дто в названии

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/feign/MarketServiceClient.java
> +@FeignClient(value = "marketService", url = "http://localhost:8081/")
url надо брать из пропертей, как потом девопс тебе сюда значение подставит. а в пропертях из переменных окружения

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/handler/impl/AddHandler.java
> +        storageService.addNewProduct(sellerId, arrParams[1], Integer.valueOf(arrParams[2]));
параметры нужно валидировать и вызов сторадж сервиса завернуть в try, он может быть не доступен или ответить ошибкой добавления, например

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/handler/impl/AllHandler.java
> +        return "Список всех пользователей \n" + client.getUsers().toString();
все сетевые вызовы надо заворачивать в try, они могут отвечать разными http кодами и это надо обрабатывать тоже

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/handler/impl/HelpHandler.java
> +    private final String HELP_TEXT = "Команды общие\n" +
static если это константа

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/handler/impl/ListHandler.java
> +                +storageService.toString();
что за storageService.toString();???
что за форматирование кода?

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/handler/impl/RequestAdminHandler.java
> +                .builder()
вот так когда пишешь вертикально лучше builder на той же строке что и класс писать, так легче читается что начался билдер этого класса

2023-04-28 14:39 UTC, sergey-oreshkin commented on gateway/src/main/java/group/megamarket/gateway/handler/impl/SetHandler.java
> +            isSeller = true;
надо валидировать оба параметра, а то ошибутся напишут amin, а ты ему продавца дашь

2023-05-01 11:55 UTC, sergey-oreshkin approved these changes

2023-05-01 12:12 UTC, iliodor1 approved these changes

2023-05-01 12:24 UTC, merged